on:
  push:
    branches:
      - "main"

name: Check compatibilty with main version
jobs:
  verify_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run the check script
      run: echo TODO