on:
  push:
  pull-request:

name: Check compatibilty with main version
jobs:
  check_compatibility_proto:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run the check script
      run: echo TODO