on:
  push:
    branches:
      - experimental

name: build-deploy-experimental-tag
jobs:
  check_and_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      dcl_protocol_s3_bucket_key: ${{ steps.publish_dcl_protocol.outputs.s3-bucket-key }}
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: make install
      - name: buf build
        run: make buf-build
      - name: build and compile test
        run: make test
      - name: publish packages
        uses: menduz/oddish-action@master
        id: publish_dcl_protocol
        with:
          custom-tag: experimental
          branch-to-custom-tag: experimental
          registry-url: 'https://registry.npmjs.org'
          access: public
          ## use action runId instead of current date to generate snapshot numbers
          deterministic-snapshot: true

          ## sign the deployment
          provenance: true

          ## publish every package to s3
          s3-bucket: ${{ secrets.SDK_TEAM_S3_BUCKET }}
          s3-bucket-key-prefix: '@dcl/protocol/branch/${{ steps.myref.outputs.branch }}'
          s3-bucket-region: ${{ secrets.SDK_TEAM_AWS_REGION }}
          ## inform gitlab after publishing to proceed with CDN propagation
          gitlab-token: ${{ secrets.GITLAB_TOKEN }}
          gitlab-pipeline-url: ${{ secrets.GITLAB_URL }}
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.SDK_TEAM_AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SDK_TEAM_AWS_SECRET }}

